#!/local/python/bin/python2

from jac_sw import uae
import numpy
import time
import socket

# version info
from subprocess import check_output
def doc(f, cmd):
    out = check_output(cmd.split())
    out = str(out.decode())
    out = out.strip().replace('\\', '\\\\').replace('"""', '\\"\\"\\"')
    f.write('\n\n=== %s ===\n\n%s' % (cmd, out))
    return out
with open('drama/version.py', 'w') as f:
    hostname = socket.gethostname()
    timestamp = time.strftime('%Y%m%d %H:%M:%S %Z')
    f.write('"""\nGenerated by setup.py on %s, %s' % (hostname, timestamp))
    description = doc(f, 'git describe --long --dirty')
    doc(f, 'git log -1 --decorate --stat')
    doc(f, 'git status')
    doc(f, 'git diff')
    f.write('\n"""\n\n__version__ = "%s"\n\n\n' % (description))

uae.setup(
    packages = ['drama'],
    ext_modules = [
        uae.Extension("drama.__drama__", ["src/drama.pyx"],
            depends=['setup.py',
                     'src/drama.pxd',
                     'src/ditsaltin.h',
                     'src/ditsmsg.h'],
            include_dirs=uae.incs + [numpy.get_include()],
            library_dirs=uae.libs,
            libraries=['jit', 'expat', 'tide', 'ca', 'Com', 'git',
                       'dul', 'dits', 'imp', 'sds', 'ers', 'mess', 'm'],
            define_macros=[("unix",None),("DPOSIX_1",None),
                           ("_GNU_SOURCE",None),("UNIX",None)],
            # preserve wrapped functions for debugging/profiling
            extra_compile_args=["-fno-inline-functions-called-once",
                                "-Wno-unreachable-code"]
        )]
)
