#!/bin/bash

OUTFILE=./drama/version.py

append() {
echo -e "\n=== $@ ===\n" >> "$OUTFILE"
$@ >> "$OUTFILE"
echo "" >> "$OUTFILE"
}

cd `dirname $0`

# This might cause problems when importing version.py
# if any 'git diff' output contains a triple-quote ---
# but I always tend to use ''' instead of """,
# so hopefully using """ here will avoid the need to escape.

echo '"""' > "$OUTFILE"
echo `whoami`@`hostname`, `date` >> "$OUTFILE"
append git describe
append git log -1 --decorate --stat
append git status
append git diff
echo '"""' >> "$OUTFILE"

